# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check for changes
      id: check_changes
      run: |
        echo "$(git status --porcelain)"
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "No changes detected. Skipping commit."
          echo "check_changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected. Committing changes."
          echo "check_changes=true" >> $GITHUB_ENV
        fi

    - name: Commit changes
      if: env.check_changes == 'true'
      run: |
        git config user.name gha
        git config user.email gha@github.com
        git add .
        git commit -m "Generating outputs [bot] [skip ci]"
        git push --force origin ${{ github.ref }}
